remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Stefano Ciapponi
description: Signal Processing researcher and engineer
repository: sciapponi/sciapponi.github.io
author:
  name: "Stefano Ciapponi"
  email: "stefano.sc.ciapponi@gmail.com"
  avatar: "/resources/img/avatar.jpg"