remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Stefano Ciapponi
description: Signal Processing researcher and engineer
repository: sciapponi/sciapponi.github.io
author:
	name: "Stefano Ciapponi"
	email: "stefano.sc.ciapponi@gmail.com"
	avatar: "https://media.licdn.com/dms/image/v2/D4D03AQGvKEGgGVPK4g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1664892035726?e=1763596800&v=beta&t=60smPLDSLdXBM-_nRy1SQVgkLfR1jksSSYYI8Xh9Rms"